instargram/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls')),
    url(r'^member/', include('member.urls')),
] + static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instargram/member/urls.py
from django.conf.urls import url

from . import views


app_name = 'member'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
]

instargram/post/urls.py
from django.conf.urls import url
from . import views


app_name = 'post'
urlpatterns = [
    # post
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<post_pk>\d+)/modify/$', views.post_modify, name='post_modify'),

    # comment
    url(r'^(?P<post_pk>\d+)/comment-create/$', views.comment_create, name='comment_create'),
    url(r'^(?P<comment_pk>\d+)/comment-modify/$', views.comment_modify, name='comment_modify'),

    # post like & unlike
    url(r'^(?P<post_pk>\d+)/post-like-toggle/$', views.post_like_toggle, name='post_like_toggle'),
]

instargram/templates/common/base.html
{% load static %}

<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Instargram</title>

    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
</head>
<body>
    <div id="wrap">
        <header class="top-header">
            <nav>
                <div class="nav-left nav-item">
                    <a href="{% url 'post:post_list' %}">
                        <img src="{% static 'images/logo.png' %}">
                    </a>
                </div>
                <div class="nav-center nav-item">
                    <input type="text" placeholder="Search...">
                </div>
                <div class="nav-right nav-item">
                    <a href="#">
                        <img src="{% static 'images/icon_explore.png' %}">
                    </a>
                    <a href="#">
                        <img src="{% static 'images/icon_heart.png' %}">
                    </a>

                    <a href="#" id="profile-icon" class="popup">
                        <img src="{% static 'images/icon_profile.png' %}">
                    </a>
                    <div id="profile-dropdown" class="dropdown-content">
                        {% if user.is_authenticated %}
                        <a href="#">{{ user }}님</a>
                        <a href="{% url 'member:logout' %}">LogOut</a>
                        <a href="#">Settings</a>
                        {% else %}
                        <a href="{% url 'member:login' %}">LogIn</a>
                        <a href="{% url 'member:signup' %}">SignUp</a>
                        {% endif %}
                    </div>
                </div>
            </nav>
        </header>
    </div>

    <div class="container">
    {% block content %}
    {% endblock %}
    </div>

    <script>
        function profileIconClickHandler(e) {
            document.getElementById("profile-dropdown").classList.toggle("show");
            e.stopPropagation();
        }

        function profileDropdownClickHandler(e) {
            e.stopPropagation();
        }

        document.getElementById("profile-icon").addEventListener(
            "click",
            profileIconClickHandler
        );

        document.getElementById("profile-dropdown").addEventListener(
            "click",
            profileDropdownClickHandler
        );

        window.addEventListener("click", function () {
            var dropdowns = document.getElementsByClassName("dropdown-content");
            var i;
            for (i = 0; i<dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                openDropdown.classList.remove('show');
            }
        });
    </script>
</body>
</html>